name: Run Unit Tests for Geometric Library

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13 

      # Шаг 3: Установка зависимостей (если требуется)
      - name: Install dependencies
        run: pip install -r requirements.txt || true

      # Шаг 4: Запуск тестов
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "unittest_*.py" -v
